version: "3"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  public:
    driver: ${VOLUME_DRIVER}

services:
  workspace:
    build:
      context: ${LOCAL_DOCKER_PATH}/workspace
      args:
        - ARG_CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
        - ARG_WORKSPACE_INSTALL_SWOOLE=${WORKSPACE_INSTALL_SWOOLE}
        - ARG_WORKSPACE_INSTALL_MONGODB=${WORKSPACE_INSTALL_MONGODB}
        - ARG_WORKSPACE_INSTALL_REDIS=${WORKSPACE_INSTALL_REDIS}
        - ARG_APP_RUN_PUID=${APP_RUN_PUID}
        - ARG_APP_RUN_PGID=${APP_RUN_PGID}
        - ARG_APP_RUN_NAME=${APP_RUN_NAME}
        - ARG_APP_RUN_GROUP=${APP_RUN_GROUP}
        - ARG_TIMEZONE=${TIMEZONE}
        - ARG_WORKSPACE_INSTALL_NPM=${WORKSPACE_INSTALL_NPM}
        - ARG_WORKSPACE_INSTALL_CRONTAB=${WORKSPACE_INSTALL_CRONTAB}
        - ARG_WORKSPACE_INSTALL_SUPERVISOR=${WORKSPACE_INSTALL_SUPERVISOR}
        - ARG_WORKSPACE_CONFIG=${WORKSPACE_CONFIG}
        - ARG_WORKSPACE_DATA=${WORKSPACE_DATA}
        - ARG_RUN_ENV=${RUN_ENV}
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${LOCAL_DOCKER_PATH}/workspace/${RUN_ENV}:${WORKSPACE_CONFIG}
    entrypoint: /usr/bin/entrypoint.sh
    command: /bin/bash
    expose:
      - 28080
    ports:
      - ${WORKSPACE_SWOOLE_PORT}:28080
    networks:
      - backend
    tty: true
  consul:
    build:
      context: ${LOCAL_DOCKER_PATH}/consul
      args:
        - ARG_CONSUL_CONFIG=${CONSUL_CONFIG}
        - ARG_CONSUL_DATA=${CONSUL_DATA}
    volumes:
      - ${LOCAL_DOCKER_PATH}/consul/config:/${CONSUL_CONFIG}
      - ${LOCAL_CODE_PATH}/storage/consul:/${CONSUL_DATA}
    entrypoint: /usr/bin/entrypoint.sh
    ports:
      - "127.0.0.1:8500:8500"
    networks:
      - frontend
      - backend
  nginx:
    build:
      context: ${LOCAL_DOCKER_PATH}/nginx
      args:
        - ARG_CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
        - ARG_APP_RUN_PUID=${APP_RUN_PUID}
        - ARG_APP_RUN_PGID=${APP_RUN_PGID}
        - ARG_APP_RUN_NAME=${APP_RUN_NAME}
        - ARG_APP_RUN_GROUP=${APP_RUN_GROUP}
        - ARG_TIMEZONE=${TIMEZONE}
        - ARG_NGINX_CONFIG=${NGINX_CONFIG}
        - ARG_RUN_ENV=${RUN_ENV}
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${LOCAL_DOCKER_PATH}/nginx/${RUN_ENV}:${NGINX_CONFIG}
    entrypoint: /usr/bin/entrypoint.sh
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_SSL_PORT}:443
    networks:
      - frontend
      - backend
    depends_on:
      - workspace
      - php-fpm
  php-fpm:
    build:
      context: ${LOCAL_DOCKER_PATH}/php-fpm
      args:
        - ARG_CONTAINER_CODE_PATH=${CONTAINER_CODE_PATH}
        - ARG_PHP_FPM_INSTALL_MONGODB=${PHP_FPM_INSTALL_MONGODB}
        - ARG_PHP_FPM_INSTALL_REDIS=${PHP_FPM_INSTALL_REDIS}
        - ARG_TIMEZONE=${TIMEZONE}
        - ARG_RUN_ENV=${RUN_ENV}
        - ARG_PHP_FPM_CONFIG=${PHP_FPM_CONFIG}
    entrypoint: /usr/bin/entrypoint.sh
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${LOCAL_DOCKER_PATH}/php-fpm/${RUN_ENV}:${PHP_FPM_CONFIG}
    expose:
      - 9000
    networks:
      - frontend
    depends_on:
      - workspace