version: "3.6"

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  public_code:
    driver: local
  public_config:
    driver: local

services:
  workspace:
    image: hellocr/microservice:workspace-latest
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${LOCAL_DOCKER_PATH}/workspace/${RUN_ENV}:${WORKSPACE_CONFIG}
    networks:
      - backend
    deploy:
      replicas: ${DEPLOY_REPLICAS}
    tty: true
  nginx:
    image: hellocr/microservice:nginx-latest
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${LOCAL_DOCKER_PATH}/nginx/${RUN_ENV}:${NGINX_CONFIG}
    networks:
      - frontend
      - backend
    deploy:
      replicas: ${DEPLOY_REPLICAS}
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_SSL_PORT}:443
#    ports:
#      - mode: host
#        protocol: tcp
#        published: 80
#        target: 80
#      - mode: host
#        protocol: tcp
#        published: 443
#        target: 443
  php-fpm:
    image: hellocr/microservice:php-fpm-latest
    volumes:
      - ${LOCAL_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${LOCAL_DOCKER_PATH}/php-fpm/${RUN_ENV}:${PHP_FPM_CONFIG}
    networks:
      - frontend
    deploy:
      replicas: ${DEPLOY_REPLICAS}